export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/artifactory/qsc_releases/software/chip/component/core-technologies.qclinux.0.0"
export TAG="260513"
export DISTRO="prebuilt_resolute"
export PACKAGE_NAME="qcom-diag_1.0.4_arm64.tar.gz"
